# recupera o evento disparado, caso seja do tipo novo commit, insere o novo commit na branch sync.
name: Catch Commit
on:
  repository_dispatch:
    types: [new-commit]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/MEDGRUPOGIT/ionic-framework"
          source_branch: "master"
          destination_branch: "sync"
          github_token: ${{ secrets.GITHUB_TOKEN }}
