#cria um pull request da branch sync para a main.
name: Sync to main

on:
  push:
    branches:
    - sync    
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: reset-sync-branch
      run: |
        git fetch origin sync:sync
        git reset --hard sync
    - name: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Novo commit detectado na master do ionic-framework. Trazendo o código para a master de med-components"
        body: ":*PR Automático*"      
        branch: sync-to-main  
        
    
