#cria um pull request da branch sync para a master.
name: Sync to Master

on:
  push:
    branches:
    - "sync"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Novo commit detectado na master do ionic-framework. Trazendo o código para a master de med-components"
        body: ":*PR Automático*"      
        base: main
        branch: sync                
        draft: false
        
    
